### ISSUE TITLE
Cannot add Group members

### ISSUE THREAD

**Issue by laserlab** [ubsuny/23-Homework1G1#1]
Let me know via discord or here who are your team members (GitHub usernames) if you cannot add them

**Comment by laserlab** [comment]
It turns out maintainers cannot add group members:

https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role

**Comment by WildJimmy** [comment]
Adding it here as suggested. My participants' github names are uarif and ahmedcode99

**Comment by laserlab** [comment]
Ok, 

I just added them. Let me know if that fixes it and then you you can close this issue.

**Comment by WildJimmy** [comment]
Good morning,

I am still missing a group member, but it may be because they didn't realize they haven't accepted the invitation. I'll mention it in class today and close the issue if that's the case. Otherwise, I assume the fix will be something simple like having to resend the link.

**Comment by laserlab** [comment]
Looks like all pending invites are closed. So you should be complete now.

**Comment by WildJimmy** [comment]
Thank you, I will be closing the issue now.
