### ISSUE TITLE
Merge request..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#10]
I am still confused, do I need to request a merge request to the maintainer of the group or the main repository?
If maintainer of the group the will the main repository maintainer will know that I have requested for merge?

**Comment by JustinJaniszewski** [comment]
You will request to merge to the main repository. However, this will only go through if the maintainer of your group accepts the merge request.  Also, I think it should notfiy them when you make the request.

**Comment by uarif** [comment]
> You will request to merge to the main repository. However, this will only go through if the maintainer of your group accepts the merge request. Also, I think it should notfiy them when you make the request.

Okay, Got you thank you

**Comment by WildJimmy** [comment]
Just to confirm, I will be notified of the merge request to the main repository. After that it's my job as maintainer to review and confirm (or deny) the request
