### ISSUE TITLE
Creating documentation file.

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#13]
Hello group members, I have forked the "23-Homework1G1" repository which "James" created. Now I am going to make a documentation file and the request James to Marge right? I can not just create a new file in the James repository for G1 right?

**Comment by WildJimmy** [comment]
Yes, that's correct. In your fork you'll write the documentation file and then create a merge request which I can approve. It's discouraged (and maybe not possible depending on your permissions?) to create the file directly in the main repository.
