### ISSUE TITLE
docstrings inside the python file

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#14]
In the documentation section, in the README file. There is written "docstrings inside the python file
" What does it mean?
Help is appreciated.

**Comment by WildJimmy** [comment]
A docstring is a string that describes the purpose of a module, method, class, or function. I think it's mainly for the readability of the code, but you can also call it directly later in a print command to immediately pull up information about the object. You can find more in depth information about it here:
https://peps.python.org/pep-0257/#what-is-a-docstring

Anyways, the point in the rubric is just that you should add the docstrings into the function so the code is more readable. Let me know if that clears it up!

**Comment by reshnashrestha** [comment]
@WildJimmy 

> A docstring is a string that describes the purpose of a module, method, class, or function. I think it's mainly for the readability of the code, but you can also call it directly later in a print command to immediately pull up information about the object. You can find more in depth information about it here: https://peps.python.org/pep-0257/#what-is-a-docstring
> 
> Anyways, the point in the rubric is just that you should add the docstrings into the function so the code is more readable. Let me know if that clears it up!

This is helpful. Thank you.
