### ISSUE TITLE
Conflict in the arithematic function chosen

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework1G1#15]
Hy.
I just saw that you guys are doing multiplication. Our group G4 is also doing the same. So, I am discussing with my group what to do next. I prefer to do addition since no other groups is performing it. I will let you know once I discuss it with my group members.

**Comment by WildJimmy** [comment]
Hello,

It is okay for us to both be working on multiplication, since there's only 4 functions and 5 groups, so one has to double up. Also, I believe G2 is working on addition if I'm not mistaken
