### ISSUE TITLE
Inaccuracy in Multiplication Algorithm

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework1G1#16]
Hi All,

While my algorithm does return a number, it tends to be very inaccurate. I know this is partially due to the nature of quantum computing, but I also know there's ways to combat this. I will continue to research ways to refine it, but please let me know if anything occurs to you

**Comment by yasmensarhan27** [comment]
I've the same problem 
Are you working on Multiplication Function ???

**Comment by yasmensarhan27** [comment]
Unfortunately, I think QC can't do the classical multiplication function

They can only do the Quantum Multiplication process

**Comment by WildJimmy** [comment]
Yes we are. I think it may have something to do with increasing the number of iterations, but I'm looking into it further and how to implement that

**Comment by yasmensarhan27** [comment]
When I searched for this, I got the following response: 
**"There is no such thing as classical multiplication using quantum computers. Quantum computers are fundamentally different from classical computers, and they cannot be used to perform classical algorithms."**

**Comment by laserlab** [comment]
@yasmensarhan27 It is always useful, (if not necessary) to add references to your quotes

**Comment by WildJimmy** [comment]
I probably should have closed this before, but I figured I'd add here that the issues #34 and #40 should give a reasonable idea of how this functions (and it returns the right result!)
