### ISSUE TITLE
Merge request. Check...

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#19]
Hi James, I just made a merge request. The file is empty, but I wanted to check whether it works or not. I guess it worked. I will make another merge request when It's complete. 
Thank you.

**Comment by laserlab** [comment]
You can also always reference your merge request (e.g. #17, this is not the one you mention. I don’t see that)

**Comment by uarif** [comment]
> You can also always reference your merge request (e.g. #17, this is not the one you mention. I don’t see that)

You mean in the title or in the description?

**Comment by WildJimmy** [comment]
You should be able to in the description. I will close this issue since we discussed the merge request with an empty file in class
