### ISSUE TITLE
Git conflict markers

### ISSUE THREAD

**Issue by laserlab** [ubsuny/23-Homework1G1#20]
Make sure you don’t have merge conflicts markers left in your files

https://github.com/ubsuny/23-Homework1G1/blob/f3e3e06adc712d4bdf0a73d0532620d9fae4ab86/quantum_multiplication_v2.py#L28

See:
https://stackoverflow.com/questions/7901864/git-conflict-markers#7901901

**Comment by WildJimmy** [comment]
Thank you for pointing this out. I'll take a look and resolve this later

**Comment by WildJimmy** [comment]
Conflict markers have been removed and code has been reformatted properly
