### ISSUE TITLE
Question about what to be include in the Algorithm, Documentation and Unit test.

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G1#23]
Do I have to include the state vector, probabilities or the Q-sphere graphs in the Algorithm or the unit test part??

What are the important things to be included??

**Comment by AhmedCode99** [comment]
You can include them if you wish. It is an open-ended question. Have fun with it.

Here is a good tutorial on how to use the unittest library:

https://www.youtube.com/watch?v=HKTyOUx9Wf4
