### ISSUE TITLE
Numbers used for multiplication..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#27]
Hi James, what numbers did you used for multiplication in the code? Is that 4*4?
Thank you.

**Comment by WildJimmy** [comment]
Hi Arif,

The 4's in the code refer to the number of qubits in the circuit (it's probably easier to see in the version without the conflict markers). The function as presented is just the definition, if you want to run it you'd have to call the function after defining it, such as by typing "quantum_multiplication(4,4)". This would give you 4*4 (or at least, 4*4 as well as the circuit will output)
