### ISSUE TITLE
Unit tests.

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#30]
Hi Ahmed, How are doing to do the unit tests? Are you going to check it the circuit too or not?

**Comment by AhmedCode99** [comment]
I do not think it is necessary to run it on a quantum computer

**Comment by AhmedCode99** [comment]
The unit test for our code is uploaded. Waiting for @WildJimmy to add it to the main branch.

BTW. Here is an excellent tutorial on using the python unittest library:

https://www.youtube.com/watch?v=HKTyOUx9Wf4
