### ISSUE TITLE
Add unit test..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#41]
Hi James, I guess Ahmed is done with the unit test. Could you please merge it? I want to see if there is any example in it.

Arif

**Comment by WildJimmy** [comment]
Hi Arif,

I don't have a merge request yet, so I'm not able to merge. @AhmedCode99 if you could send me a merge request I can do that ASAP. Also, if you're already done with the unit test no worries on the changes mentioned earlier in issues #38 #39 #40. I'll add them quick to resolve issues of too large/negative numbers/whatever

**Comment by WildJimmy** [comment]
@uarif In the meantime you should be able to see his unit test file at https://github.com/AhmedCode99/HW1_UnitTest/blob/Multiplication-Unit-Test/multiplication_unittest.ipynb, so hopefully you can still use it as a reference!
