### ISSUE TITLE
Code doesn't work with me.

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#43]
Hi James, I tried running the code on different platforms but it is not working IDK why,..

**Comment by WildJimmy** [comment]
Hi Arif,

Could you give an example of the error you're getting? Also if you're not running it in the IBM Quantum environment that could be part of the issue as mentioned in #42

**Comment by AhmedCode99** [comment]
@uarif You must have qiskit and qiskit-aer libraries installed in your environment.
