### ISSUE TITLE
output is 11.

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework1G1#46]
Hi G1 team,

I don't see what input you guys are taking in but the output is always 11. I wonder how the code is throwing out the value. Also, you guys are importing numpy library which I don't use it being used in the code.

**Comment by WildJimmy** [comment]
I'm confused as to why you'd consistently be getting 11, it still runs correctly for me (I'm using the IBM quantum lab). What environment are you using? And are you using the latest version that's on main?

For numpy, that's a holdover from when I was attempting to assemble the circuit at a more fundamental level (needed pi for phase shifts, but that ended up getting too complicated.) I think you're right that it's not necessary anymore

**Comment by s4il3sh** [comment]
@WildJimmy right! maybe i am using different environment. Well, I tested it on the jupyter notebook with qiskit running in it. Let me try that on the IBM Quantum lab.

**Comment by AhmedCode99** [comment]
@s4il3sh I tried the code several times. It works perfectly if you multiply small positive integers.
