### ISSUE TITLE
Which operator should we choose

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework1G1#6]
Sorry for the delay everybody. Now that we're all set up, which operator should we choose for our project? It looks like the 4 other groups have chosen a different one each, so we can pick whichever. I personally suggest multiplication.

**Comment by uarif** [comment]
Yes, Multiplication is okay. Lets go with multiplication.

**Comment by uarif** [comment]
Also, we have to specify our task too right?, which person, in the group will do which part?

**Comment by WildJimmy** [comment]
I can do the algorithm since I have some more coding experience if that's okay. I will likely complete it after class tomorrow since then I'll have a little more of a primer on coding for the quantum computer

**Comment by uarif** [comment]
> I can do the algorithm since I have some more coding experience if that's okay. I will likely complete it after class tomorrow since then I'll have a little more of a primer on coding for the quantum computer

Fine with me, lets wait for @AhmedCode99

**Comment by AhmedCode99** [comment]
Multiplication is fine. So @WildJimmy is doing the code, and @uarif is doing the documentation? I guess that leaves me with the unit test. I can start working on that Thursday night or Friday morning.

**Comment by AhmedCode99** [comment]
Are we just working on multiplying integers? Or do we consider all real numbers?

**Comment by uarif** [comment]
I think we will just do multiplication between two real numbers. But let's hear from @WildJimmy too.

**Comment by WildJimmy** [comment]
I would assume just integers, but it depends how hard it is to implement it for all reals. If it's easy to do for all reals then I think we should do that. I will update once I finish the algorithm

**Comment by AhmedCode99** [comment]
The multiplication of integers has been decided upon.

**Comment by WildJimmy** [comment]
Since we have decided on the operator I will close the issue now. We can discuss reals/integers and other topics in new issues

Edit: issue was closed right as I was typing this
