### ISSUE TITLE
Pull request..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G1#60]
Can you please check whether you got a pull request from me? I have recently made one. @WildJimmy

**Comment by AhmedCode99** [comment]
I think everything is merged now

**Comment by uarif** [comment]
No, its not, that is the old file for documentation.

**Comment by AhmedCode99** [comment]
@WildJimmy please merge the documentation file

**Comment by WildJimmy** [comment]
I have now received and confirmed the merge request
